[application]

[web.app]

# HTML title tag content
title = "morph-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.config]
# Замените 'название_репозитория' на реальное имя вашего репозитория на GitHub
base_path = "greek_app"