[application]

[web.app]

# HTML title tag content
title = "morph-app"

# GitHub Pages subdirectory prefix (baked into WASM binary at build time)
base_path = "greek_app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []